### ISSUE TITLE
代码疑问，这里是不是反了？

### ISSUE THREAD

**Issue by junranhe** [xingdi-eric-yuan/single-layer-convnet#1]
Convnet.cpp 312行， 
Rect roi = Rect(j \* pVert, i \* pHori, pVert, pHori);

读了下代码， i和j位置是不是反了？
Rect roi = Rect(i\* pVert, j \* pHori, pVert, pHori);

**Comment by xingdi-eric-yuan** [comment]
@junranhe 多谢关注，这行确实有问题，但是问题不是i和j反了。
在openCV里矩形的定义是Rect(左上角横坐标，左上角纵坐标，width， height)。所以i和j没问题，问题是pVert和pHori反了。这个版本很久没维护了，里面好多小bug，可以看看新写的版本https://github.com/xingdi-eric-yuan/conv-net-version-3

**Comment by xingdi-eric-yuan** [comment]
@junranhe btw，在代码里已经修改了这一处以及pooling函数里的响应几个地方。

**Comment by junranhe** [comment]
你代码很好啊，我是朋友介绍我看你的代码的，他说你几乎每篇博客他都看了，了解深度学习直接看你代码会比较好

**Comment by junranhe** [comment]
以后有代码的疑问还是要多请教你啊
